"""add_isbn_and_source_fields

Revision ID: 9c87a9c6fe7d
Revises: d0fac85afd0f
Create Date: 2026-01-20 09:22:02.210881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c87a9c6fe7d'
down_revision: Union[str, None] = 'd0fac85afd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audiobook", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("isbn_10", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("isbn_13", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("google_books_id", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("source", sa.String(), nullable=False, server_default="audible")
        )
        batch_op.create_index("ix_audiobook_isbn_10", ["isbn_10"])
        batch_op.create_index("ix_audiobook_isbn_13", ["isbn_13"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audiobook", schema=None) as batch_op:
        batch_op.drop_index("ix_audiobook_isbn_13")
        batch_op.drop_index("ix_audiobook_isbn_10")
        batch_op.drop_column("source")
        batch_op.drop_column("google_books_id")
        batch_op.drop_column("isbn_13")
        batch_op.drop_column("isbn_10")

    # ### end Alembic commands ###
