"""separate cached books table

Revision ID: d0fac85afd0f
Revises: 03bea7e891dd
Create Date: 2025-12-31 12:19:10.276655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "d0fac85afd0f"
down_revision: Union[str, None] = "03bea7e891dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audiobook",
        sa.Column("asin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subtitle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("authors", sa.JSON(), nullable=True),
        sa.Column("narrators", sa.JSON(), nullable=True),
        sa.Column("cover_image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("release_date", sa.DateTime(), nullable=False),
        sa.Column("runtime_length_min", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("downloaded", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("asin"),
    )

    if op.get_bind().dialect.name == "sqlite":
        op.execute("""WITH requested_audiobooks AS (
                        SELECT asin, title, subtitle, authors, narrators, cover_image, release_date, runtime_length_min, updated_at, downloaded,
                            ROW_NUMBER() OVER (PARTITION BY asin ORDER BY updated_at DESC) as rn
                        FROM bookrequest
                        WHERE user_username IS NOT NULL)
                    INSERT INTO audiobook (asin, title, subtitle, authors, narrators, cover_image, release_date, runtime_length_min, updated_at, downloaded)
                    SELECT asin, title, subtitle, authors, narrators, cover_image, release_date, runtime_length_min, updated_at, downloaded
                    FROM requested_audiobooks
                    WHERE rn = 1
                    """)
    elif op.get_bind().dialect.name == "postgresql":
        op.execute("""INSERT INTO audiobook (asin, title, subtitle, authors, narrators, cover_image, release_date, runtime_length_min, updated_at, downloaded)
                    SELECT DISTINCT ON (asin) asin, title, subtitle, authors, narrators, cover_image, release_date, runtime_length_min, updated_at, downloaded
                    FROM bookrequest
                    WHERE user_username IS NOT NULL""")
    else:
        raise NotImplementedError("Unsupported database dialect")

    op.create_table(
        "audiobookrequest",
        sa.Column("asin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asin"], ["audiobook.asin"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_username"], ["user.username"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("asin", "user_username"),
    )

    op.execute("""INSERT INTO audiobookrequest (asin, user_username, updated_at)
                SELECT asin, user_username, updated_at FROM bookrequest WHERE user_username IS NOT NULL""")

    op.drop_table("bookrequest")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookrequest",
        sa.Column("user_username", sa.VARCHAR(), nullable=True),
        sa.Column("title", sa.VARCHAR(), nullable=False),
        sa.Column("subtitle", sa.VARCHAR(), nullable=True),
        sa.Column("authors", sqlite.JSON(), nullable=True),
        sa.Column("narrators", sqlite.JSON(), nullable=True),
        sa.Column("cover_image", sa.VARCHAR(), nullable=True),
        sa.Column("release_date", sa.DateTime(), nullable=False),
        sa.Column("runtime_length_min", sa.Integer(), nullable=False),
        sa.Column("asin", sa.VARCHAR(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "downloaded",
            sa.BOOLEAN(),
            server_default=sa.text("'false'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_username"],
            ["user.username"],
            name=op.f("user_user_username"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookrequest")),
        sa.UniqueConstraint("asin", "user_username", name=op.f("unique_asin_user")),
    )

    if op.get_bind().dialect.name == "sqlite":
        op.execute("""INSERT INTO bookrequest (id, asin, title, subtitle, authors, narrators, cover_image, release_date, runtime_length_min, updated_at, downloaded, user_username)
                    SELECT lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))),
                        a.asin, a.title, a.subtitle, a.authors, a.narrators, a.cover_image, a.release_date, a.runtime_length_min, a.updated_at, a.downloaded, ar.user_username
                    FROM audiobook AS a
                    LEFT JOIN audiobookrequest AS ar ON a.asin = ar.asin""")
    elif op.get_bind().dialect.name == "postgresql":
        op.execute("""INSERT INTO bookrequest (id, asin, title, subtitle, authors, narrators, cover_image, release_date, runtime_length_min, updated_at, downloaded, user_username)
                    SELECT gen_random_uuid(), a.asin, a.title, a.subtitle, a.authors, a.narrators, a.cover_image, a.release_date, a.runtime_length_min, a.updated_at, a.downloaded, ar.user_username
                    FROM audiobook AS a
                    LEFT JOIN audiobookrequest AS ar ON a.asin = ar.asin""")
    else:
        raise NotImplementedError("Unsupported database dialect")

    op.drop_table("audiobookrequest")
    op.drop_table("audiobook")
    # ### end Alembic commands ###
